#!/usr/bin/env node

const fs = require('fs');
const traverse = require('@babel/traverse').default;
const XmlWriter = require('xml-writer');

const generateXmlFromAst = (ast) => {
  const xml = new XmlWriter(true);
  xml.startDocument();

  traverse(ast, {
    enter: function ({ node }) {
      xml.startElement('tree');
      xml.writeAttribute('type', node.type);
      xml.writeAttribute('pos', node.start);
      xml.writeAttribute('length', node.end - node.start);

      if (node.type === 'Identifier') xml.writeAttribute('label', node.name);
      else if (node.type === 'Literal') xml.writeAttribute('label', node.raw);
    },
    exit: function () {
      xml.endElement();
    },
  });

  xml.endDocument();
  return xml.toString();
};

const main = () => {
  const filePath = process.argv[2];
  if (!filePath) {
    console.error('Please provide a file path as an argument.');
    process.exit(1);
  }

  const ast = fs.readFileSync(filePath, 'utf8');
  const xmlString = generateXmlFromAst(JSON.parse(ast));
  console.log(xmlString);
};

main();
